mod 'puppet/nginx'
mod 'puppetlabs/stdlib'
mod 'puppetlabs-apt', '6.0.0'
mod 'puppetlabs-translate', '1.1.0'
mod 'puppetlabs-powershell', '2.1.5'
mod 'puppetlabs-reboot', '2.0.0'
mod 'puppetlabs/concat'
mod 'pltraining/dockeragent'
mod 'puppetlabs-docker', '2.0.0'
